---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts/{post_id}/comments":
    get:
      summary: Retrieve list of comments for a given post
      tags:
      - Comments
      security:
      - bearer_auth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    author_id:
                      type: integer
                    post_id:
                      type: integer
                    text:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                required:
                - id
                - text
                - author_id
                - post_id
        '401':
          description: unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
    post:
      summary: Create a new comment for a given post
      tags:
      - Comments
      security:
      - bearer_auth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      - name: post_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: comment created
        '302':
          description: user not signed-in, redirecting to sign_in route
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
              required:
              - text
  "/api/users/{user_id}/posts":
    get:
      summary: Retrieve list of posts for a given user
      tags:
      - Posts
      security:
      - bearer_auth: []
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: name found
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    author_id:
                      type: integer
                    title:
                      type: string
                    text:
                      type: string
                    comments_counter:
                      type: integer
                    likes_counter:
                      type: integer
                    created_at:
                      type: string
                    updated_at:
                      type: string
                required:
                - id
                - title
                - text
                - comments_counter
                - likes_counter
        '401':
          description: unauthorized request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                - error
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
